In [145]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (15,10)

In [146]:
df = pd.read_csv('bengaluru_house_prices.csv')
df.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [147]:
df1 = df.drop(['area_type','availability','society','balcony'],axis = 'columns')
df1.head()

location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [148]:
df1.shape

(13320, 5)

In [149]:
df1.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [150]:
df2 = df1.dropna()

In [151]:
df2.isna().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [152]:
df2['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [153]:
df2['rooms'] = df2['size'].apply(lambda x: int(x.split(' ')[0]))
df2.head()

<ipython-input-153-016c5b484cc1>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['rooms'] = df2['size'].apply(lambda x: int(x.split(' ')[0]))


location       size total_sqft  bath   price  rooms
0  Electronic City Phase II      2 BHK       1056   2.0   39.07      2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00      4
2               Uttarahalli      3 BHK       1440   2.0   62.00      3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00      3
4                  Kothanur      2 BHK       1200   2.0   51.00      2

In [154]:
df3 = df2.drop('size',axis = 'columns')
df3.head()

location total_sqft  bath   price  rooms
0  Electronic City Phase II       1056   2.0   39.07      2
1          Chikka Tirupathi       2600   5.0  120.00      4
2               Uttarahalli       1440   2.0   62.00      3
3        Lingadheeranahalli       1521   3.0   95.00      3
4                  Kothanur       1200   2.0   51.00      2

In [155]:
df3.shape

(13246, 5)

In [156]:
df3['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [157]:
def sqft(x):
    y = x.split('-')
    if len(y)==2:
        return(float(y[0])+float(y[1]))/2
    try:
        return (float(x))
    except:
        return None
df3['total_sqft'] = df3['total_sqft'].apply(sqft)

In [158]:
df3['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [159]:
df3['price'] = df3['price'].apply(lambda x: float(x))
df3['bath'] = df3['bath'].apply(lambda x: float(x))
df3.sample(10)

location  total_sqft  bath   price  rooms
9723               JP Nagar      1500.0   2.0   87.00      4
4804         Kanakpura Road       700.0   2.0   34.98      2
10055            Nagarbhavi      1350.0   3.0   60.00      3
8090           Channasandra      1093.0   2.0   34.00      2
4525       Shirdi Sai Nagar      1200.0   3.0   85.00      3
227    Shantiniketan Layout      1500.0   2.0  115.00      2
4759         Sarjapur  Road      1230.0   2.0   94.50      2
13204            Dasanapura       814.0   2.0   43.70      2
5267            Vijayanagar      1300.0   2.0   75.00      3
11881          Bannerghatta      1320.0   2.0   50.00      2

In [160]:
df3['price_per_sqft'] = df3['price']*100000/df3['total_sqft']
df3.head()

location  total_sqft  bath   price  rooms  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07      2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00      4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00      3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00      3     6245.890861
4                  Kothanur      1200.0   2.0   51.00      2     4250.000000

In [161]:
df3.location = df3.location.apply(lambda x: x.strip())
no_of_location = df3['location'].value_counts()
no_of_location

Whitefield               535
Sarjapur  Road           392
Electronic City          304
Kanakpura Road           266
Thanisandra              236
                        ... 
Uvce Layout                1
NTI Layout                 1
Reliable Woods Layout      1
Ckikkakammana Halli        1
Duddanahalli               1
Name: location, Length: 1293, dtype: int64

In [162]:
len(no_of_location)

1293

In [163]:
location_under_10 = no_of_location[no_of_location<=10]
location_under_10.unique()

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1], dtype=int64)

In [164]:
df3.location = df3.location.apply(lambda x: 'other' if x in location_under_10 else x)
len(df3['location'].unique())

242

In [165]:
df3.head()

location  total_sqft  bath   price  rooms  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07      2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00      4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00      3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00      3     6245.890861
4                  Kothanur      1200.0   2.0   51.00      2     4250.000000

In [166]:
df4 = df3[df3['total_sqft']/df3['rooms']>=300]
df4.shape

(12456, 6)

In [167]:
df4.describe()

total_sqft          bath         price         rooms  price_per_sqft
count  12456.000000  12456.000000  12456.000000  12456.000000    12456.000000
mean    1590.189927      2.562781    111.187960      2.649004     6308.502826
std     1260.404795      1.080275    152.203367      0.976046     4168.127339
min      300.000000      1.000000      9.000000      1.000000      267.829813
25%     1115.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [168]:
u = df4['price_per_sqft'].mean()+df4['price_per_sqft'].std()
l = df4['price_per_sqft'].mean()-df4['price_per_sqft'].std()
u,l

(10476.630164555358, 2140.3754875406403)

In [169]:
df4[(df4['price_per_sqft']>u)|(df4['price_per_sqft']<l)]

location  total_sqft  bath  price  rooms  price_per_sqft
7        Rajaji Nagar      3300.0   4.0  600.0      4    18181.818182
11         Whitefield      2785.0   5.0  295.0      4    10592.459605
22        Thanisandra      2800.0   5.0  380.0      4    13571.428571
48           KR Puram       800.0   1.0  130.0      2    16250.000000
57              other      1500.0   2.0  185.0      2    12333.333333
...               ...         ...   ...    ...    ...             ...
13290  Sarjapur  Road      4050.0   2.0  450.0      4    11111.111111
13296        Cox Town      1200.0   2.0  140.0      2    11666.666667
13305        Hulimavu       500.0   1.0  220.0      1    44000.000000
13306           other      1200.0   5.0  325.0      4    27083.333333
13316           other      3600.0   5.0  400.0      4    11111.111111

[1162 rows x 6 columns]

In [170]:
df5 = df4[(df4['price_per_sqft']<u)&(df4['price_per_sqft']>l)]
df5.head()

location  total_sqft  bath   price  rooms  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07      2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00      4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00      3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00      3     6245.890861
4                  Kothanur      1200.0   2.0   51.00      2     4250.000000

In [171]:
df5.shape

(11294, 6)

In [172]:
df5[df5.bath>df5.rooms+2]

location  total_sqft  bath   price  rooms  price_per_sqft
2620           other     11338.0   9.0  1000.0      6     8819.897689
7709   Chikkabanavar      2460.0   7.0    80.0      4     3252.032520
11366     Nagasandra      7000.0   8.0   450.0      4     6428.571429
12103    Thanisandra      1806.0   6.0   116.0      3     6423.034330

In [173]:
df6 = df5[df5.bath<df5.rooms+2]
df6.head()

location  total_sqft  bath   price  rooms  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07      2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00      4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00      3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00      3     6245.890861
4                  Kothanur      1200.0   2.0   51.00      2     4250.000000

In [174]:
df6.shape

(11198, 6)

In [175]:
df5.shape[0]-df6.shape[0]

96

In [176]:
dummy = pd.get_dummies(df6['location'])
dummy.head()

1st Block Jayanagar  1st Phase JP Nagar  2nd Phase Judicial Layout  \
0                    0                   0                          0   
1                    0                   0                          0   
2                    0                   0                          0   
3                    0                   0                          0   
4                    0                   0                          0   

   2nd Stage Nagarbhavi  5th Block Hbr Layout  5th Phase JP Nagar  \
0                     0                     0                   0   
1                     0                     0                   0   
2                     0                     0                   0   
3                     0                     0                   0   
4                     0                     0                   0   

   6th Phase JP Nagar  7th Phase JP Nagar  8th Phase JP Nagar  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   9th Phase JP Nagar  ...  Vishveshwarya Layout  Vishwapriya Layout  \
0                   0  ...                     0                   0   
1                   0  ...                     0                   0   
2                   0  ...                     0                   0   
3                   0  ...                     0                   0   
4                   0  ...                     0                   0   

   Vittasandra  Whitefield  Yelachenahalli  Yelahanka  Yelahanka New Town  \
0            0           0               0          0                   0   
1            0           0               0          0                   0   
2            0           0               0          0                   0   
3            0           0               0          0                   0   
4            0           0               0          0                   0   

   Yelenahalli  Yeshwanthpur  other  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0  

[5 rows x 241 columns]

In [177]:
df7 = pd.concat([df6,dummy],axis = 'columns')
df7.head()

location  total_sqft  bath   price  rooms  price_per_sqft  \
0  Electronic City Phase II      1056.0   2.0   39.07      2     3699.810606   
1          Chikka Tirupathi      2600.0   5.0  120.00      4     4615.384615   
2               Uttarahalli      1440.0   2.0   62.00      3     4305.555556   
3        Lingadheeranahalli      1521.0   3.0   95.00      3     6245.890861   
4                  Kothanur      1200.0   2.0   51.00      2     4250.000000   

   1st Block Jayanagar  1st Phase JP Nagar  2nd Phase Judicial Layout  \
0                    0                   0                          0   
1                    0                   0                          0   
2                    0                   0                          0   
3                    0                   0                          0   
4                    0                   0                          0   

   2nd Stage Nagarbhavi  ...  Vishveshwarya Layout  Vishwapriya Layout  \
0                     0  ...                     0                   0   
1                     0  ...                     0                   0   
2                     0  ...                     0                   0   
3                     0  ...                     0                   0   
4                     0  ...                     0                   0   

   Vittasandra  Whitefield  Yelachenahalli  Yelahanka  Yelahanka New Town  \
0            0           0               0          0                   0   
1            0           0               0          0                   0   
2            0           0               0          0                   0   
3            0           0               0          0                   0   
4            0           0               0          0                   0   

   Yelenahalli  Yeshwanthpur  other  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0  

[5 rows x 247 columns]

In [178]:
df8 = df7.drop(['location','other'],axis = 'columns')
df8.head()

total_sqft  bath   price  rooms  price_per_sqft  1st Block Jayanagar  \
0      1056.0   2.0   39.07      2     3699.810606                    0   
1      2600.0   5.0  120.00      4     4615.384615                    0   
2      1440.0   2.0   62.00      3     4305.555556                    0   
3      1521.0   3.0   95.00      3     6245.890861                    0   
4      1200.0   2.0   51.00      2     4250.000000                    0   

   1st Phase JP Nagar  2nd Phase Judicial Layout  2nd Stage Nagarbhavi  \
0                   0                          0                     0   
1                   0                          0                     0   
2                   0                          0                     0   
3                   0                          0                     0   
4                   0                          0                     0   

   5th Block Hbr Layout  ...  Vijayanagar  Vishveshwarya Layout  \
0                     0  ...            0                     0   
1                     0  ...            0                     0   
2                     0  ...            0                     0   
3                     0  ...            0                     0   
4                     0  ...            0                     0   

   Vishwapriya Layout  Vittasandra  Whitefield  Yelachenahalli  Yelahanka  \
0                   0            0           0               0          0   
1                   0            0           0               0          0   
2                   0            0           0               0          0   
3                   0            0           0               0          0   
4                   0            0           0               0          0   

   Yelahanka New Town  Yelenahalli  Yeshwanthpur  
0                   0            0             0  
1                   0            0             0  
2                   0            0             0  
3                   0            0             0  
4                   0            0             0  

[5 rows x 245 columns]

In [179]:
x = df8.drop('price',axis = 'columns')
x.head(2)

total_sqft  bath  rooms  price_per_sqft  1st Block Jayanagar  \
0      1056.0   2.0      2     3699.810606                    0   
1      2600.0   5.0      4     4615.384615                    0   

   1st Phase JP Nagar  2nd Phase Judicial Layout  2nd Stage Nagarbhavi  \
0                   0                          0                     0   
1                   0                          0                     0   

   5th Block Hbr Layout  5th Phase JP Nagar  ...  Vijayanagar  \
0                     0                   0  ...            0   
1                     0                   0  ...            0   

   Vishveshwarya Layout  Vishwapriya Layout  Vittasandra  Whitefield  \
0                     0                   0            0           0   
1                     0                   0            0           0   

   Yelachenahalli  Yelahanka  Yelahanka New Town  Yelenahalli  Yeshwanthpur  
0               0          0                   0            0             0  
1               0          0                   0            0             0  

[2 rows x 244 columns]

In [180]:
y = df8['price']
y.head(2)

0     39.07
1    120.00
Name: price, dtype: float64

In [181]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

In [210]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [183]:
cross_val_score(LinearRegression(),x,y)

array([ 9.69694078e-01,  9.50228975e-01,  9.40040221e-01, -8.57885300e+10,
        9.52145471e-01])

In [184]:
cross_val_score(Lasso(),x,y)

array([0.96676845, 0.94841869, 0.9385988 , 0.95440098, 0.94995437])

In [187]:
model_params = {
    'linear reg':{
        'model':LinearRegression(),
        'params':{
            'normalize':[True,False]
        }
    },
    'lasso reg':{
        'model':Lasso(),
        'params':{
            'selection':['cyclic', 'random'],
            'alpha':[1,2,3],
            'normalize':[True,False]
        }
    }
}

In [189]:
scores = []
for model_name,mp in model_params.items():
    cls = GridSearchCV(mp['model'],mp['params'],cv = 5,return_train_score=False)
    cls.fit(x,y)
    scores.append({
        'model_name':model_name,
        'best_score':cls.best_score_,
        'best_params':cls.best_params_
    })

In [190]:
best_model = pd.DataFrame(scores,columns = ['model_name','best_score','best_params'])
best_model

model_name  best_score                                        best_params
0  linear reg    0.953870                                {'normalize': True}
1   lasso reg    0.951628  {'alpha': 1, 'normalize': False, 'selection': ...

In [191]:
model = LinearRegression(normalize=True)

In [211]:
model.fit(x_train,y_train)

LinearRegression(normalize=True)

In [212]:
model.score(x_test,y_test)

0.9522060990431952