In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [32]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x:iris.target_names[x])

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [13]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size = 0.3)

In [20]:
from sklearn.svm import SVC

In [21]:
model = SVC(kernel = 'rbf',C = 30,gamma = 'auto')

In [22]:
model.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [23]:
model.score(x_test,y_test)

0.9333333333333333

In [24]:
from sklearn.model_selection import cross_val_score

In [28]:
cross_val_score(SVC(kernel = 'linear',C = 10,gamma = 'auto'),iris.data,iris.target,cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [29]:
cross_val_score(SVC(kernel = 'rbf',C = 10,gamma = 'auto'),iris.data,iris.target,cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [30]:
cross_val_score(SVC(kernel = 'rbf',C = 20,gamma = 'auto'),iris.data,iris.target,cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [34]:
kernels = ['rbf','linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel = kval,gamma = 'auto',C = cval),iris.data,iris.target,cv = 5)
        avg_scores[kval+'_'+str(cval)] =np.average(cv_scores)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [35]:
from sklearn.model_selection import GridSearchCV

In [37]:
clf = GridSearchCV(SVC(gamma = 'auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv = 5, return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00030303, 0.00025854, 0.00039902, 0.00019941, 0.00019937,
        0.00059834]),
 'std_fit_time': array([0.00040108, 0.00051708, 0.00048869, 0.00039883, 0.00039873,
        0.00048854]),
 'mean_score_time': array([0.00019979, 0.0003994 , 0.        , 0.00019941, 0.00039916,
        0.        ]),
 'std_score_time': array([0.00039959, 0.00048916, 0.        , 0.00039883, 0.00048887,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [38]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000303      0.000401         0.000200        0.000400       1   
1       0.000259      0.000517         0.000399        0.000489       1   
2       0.000399      0.000489         0.000000        0.000000      10   
3       0.000199      0.000399         0.000199        0.000399      10   
4       0.000199      0.000399         0.000399        0.000489      20   
5       0.000598      0.000489         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [39]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [40]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [42]:
clf.best_score_

0.9800000000000001

In [43]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [63]:
rs = RandomizedSearchCV(SVC(gamma = 'auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv = 5,return_train_score = False,n_iter = 2)

In [64]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [65]:
df = pd.DataFrame(rs.cv_results_)

In [66]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear             0.98
1      10          rbf             0.98

In [67]:
rs.best_score_

0.9800000000000001

In [68]:
rs.best_params_

{'kernel': 'linear', 'C': 1}

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [72]:
model_params = {
    'svm':{
        'model':SVC(gamma = 'auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver = 'liblinear',multi_class = 'auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [75]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv = 5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

In [78]:
df = pd.DataFrame(scores,columns = ['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}